routes/admin.php
<?php
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->namespace('Admin')->group(function (){

    // login
    Route::get('/login', [
        'as' => 'admin.login',
        'uses' => 'AdminController@login'
    ]);
    Route::post('/login', [
        'as' => 'admin.login',
        'uses' => 'AdminController@post_login'
    ]);

    // Dashboard
    Route::get('dashboard',[
        'uses' => 'MemberController@showDashboard',
        'as' => 'admin.dashboard',
        'middleware' => 'can:view-dashboard'
    ]);

    // Category
    Route::prefix('categories')->group(function (){
        Route::get('/',[
            'uses' => 'CategoryController@index',
            'as' => 'categories.index',
            'middleware' => 'can:view-category'
        ]);
        Route::get('list-category',[
            'uses' => 'CategoryController@listCategory',
            'as' => 'categories.list'
        ]);
        Route::get('list-parent',[
            'uses' => 'CategoryController@listParent',
            'as' => 'categories.list-parent'
        ]);
        Route::post('store',[
            'uses' => 'CategoryController@store',
            'as' => 'categories.store',
            'middleware' => 'can:add-category'
        ]);
        Route::post('update/{id}',[
            'uses' => 'CategoryController@update',
            'as' => 'categories.update',
            'middleware' => 'can:edit-category'
        ]);
        Route::get('get-category/{id}',[
            'uses' => 'CategoryController@getCategory',
            'as' => 'categories.get-category'
        ]);
        Route::get('destroy/{id}',[
            'uses' => 'CategoryController@destroy',
            'as' => 'categories.destroy',
            'middleware' => 'can:delete-category'
        ]);
        Route::get('change-status/{id}',[
            'uses' => 'CategoryController@changeStatus',
            'as' => 'categories.change-status',
            'middleware' => 'can:edit-category'
        ]);
        Route::get('tree-view',[
            'uses'=>'CategoryController@treeView',
            'as'=>'categories.tree-view'
        ]);
    });

    // Product
    Route::prefix('products')->group(function(){
        Route::get('/',[
            'uses' => 'ProductController@index',
            'as' => 'products.index',
            'middleware' => 'can:view-product'
        ]);
        Route::get('list-product',[
            'uses'=>'ProductController@listProduct',
            'as'=>'products.list'
        ]);
        Route::get('change-status/{id}',[
            'uses'=>'ProductController@changeStatus',
            'as'=>'products.change-status',
            'middleware' => 'can:edit-product'
        ]);
        Route::post('store',[
            'uses'=>'ProductController@store',
            'as'=>'products.store',
            'middleware' => 'can:add-product'
        ]);
        Route::post('update/{id}',[
            'uses'=>'ProductController@update',
            'as'=>'products.update',
            'middleware' => 'can:edit-product'
        ]);
        Route::get('edit/{id}',[
            'uses'=>'ProductController@edit',
            'as'=>'products.edit',
            'middleware' => 'can:edit-product'
        ]);
        Route::get('destroy/{id}',[
            'uses'=>'ProductController@destroy',
            'as'=>'products.destroy',
            'middleware' => 'can:delete-product'
        ]);
    });

    // Article
    Route::prefix('articles')->group(function () {
        Route::get('/',[
            'uses' => 'ArticleController@index',
            'as' => 'articles.index',
            'middleware' => 'can:view-article'
        ]);
        Route::get('/create',[
            'uses' => 'ArticleController@create',
            'as' => 'articles.create',
            'middleware' => 'can:add-article'
        ]);
        Route::post('/store',[
            'uses' => 'ArticleController@store',
            'as' => 'articles.store',
            'middleware' => 'can:add-article'
        ]);
        Route::get('/{id}/edit', [
            'uses' => 'ArticleController@edit',
            'as' => 'articles.edit',
            'middleware' => 'can:edit-article'
        ]);
        Route::post('/{id}/update', [
            'uses' => 'ArticleController@update',
            'as' => 'articles.update',
            'middleware' => 'can:edit-article'
        ]);
        Route::get('/{id}/destroy',[
            'uses' => 'ArticleController@destroy',
            'as' => 'articles.destroy',
            'middleware' => 'can:delete-article'
        ]);
    });

    // users
    Route::prefix('users')->group(function () {
        Route::get('/', [
            'uses' => 'UserController@index',
            'as' => 'users.index',
            'middleware' => 'can:view-user'
        ]);

        Route::get('/create',[
            'uses' => 'UserController@create',
            'as' => 'users.create',
            'middleware' => 'can:add-user'
        ]);
        Route::post('/store',[
            'uses' => 'UserController@store',
            'as' => 'users.store',
            'middleware' => 'can:add-user'
        ]);
        Route::get('/{id}/edit', [
            'uses' => 'UserController@edit',
            'as' => 'users.edit',
            'middleware' => 'can:edit-user'
        ]);
        Route::post('/{id}/update', [
            'uses' => 'UserController@update',
            'as' => 'users.update',
            'middleware' => 'can:edit-user'
        ]);
        Route::get('/{id}/destroy',[
            'uses' => 'UserController@destroy',
            'as' => 'users.destroy',
            'middleware' => 'can:delete-user'
        ]);
    });

    // roles
    Route::prefix('roles')->group(function () {
        Route::get('/', [
            'uses' => 'RoleController@index',
            'as' => 'roles.index',
            'middleware' => 'can:view-role'
        ]);

        Route::get('/create',[
            'uses' => 'RoleController@create',
            'as' => 'roles.create',
            'middleware' => 'can:add-role'
        ]);
        Route::post('/store',[
            'uses' => 'RoleController@store',
            'as' => 'roles.store',
            'middleware' => 'can:add-role'
        ]);
        Route::get('/{id}/edit', [
            'uses' => 'RoleController@edit',
            'as' => 'roles.edit',
            'middleware' => 'can:edit-role'
        ]);
        Route::post('/{id}/update', [
            'uses' => 'RoleController@update',
            'as' => 'roles.update',
            'middleware' => 'can:edit-role'
        ]);
        Route::get('/{id}/destroy',[
            'uses' => 'RoleController@destroy',
            'as' => 'roles.destroy',
            'middleware' => 'can:delete-role'
        ]);
    });

    Route::prefix('orders')->group(function () {
        Route::get('/', [
            'uses' => 'OrderController@index',
            'as' => 'orders.index'
        ]);

        Route::get('detail/{id}', [
            'uses' => 'OrderController@detail',
            'as' => 'orders.detail'
        ]);

        Route::get('status-to-transport/{id}', [
            'uses' => 'OrderController@changeStatusToTransport',
            'as' => 'orders.status-to-transport'
        ]);

        Route::get('status-to-done/{id}', [
            'uses' => 'OrderController@changeStatusToDone',
            'as' => 'orders.status-to-done'
        ]);
    });
});

routes/frontend.php
<?php
use Illuminate\Support\Facades\Route;

Route::prefix('frontend')->as('frontend.')->namespace('Frontend')->group(function () {
    Route::get('/',[
        'uses' => 'HomeController@index',
        'as' => 'index'
    ]);

    Route::post('login', [
        'uses' => 'HomeController@login',
        'as' => 'login'
    ]);

    Route::post('register', [
        'uses' => 'HomeController@register',
        'as' => 'register'
    ]);

    Route::get('logout', [
        'uses' => 'HomeController@logout',
        'as' => 'logout'
    ]);

    Route::get('show-categories/{slug}/{id}', [
        'uses' => 'HomeController@showCategory',
        'as' => 'show-categories'
    ]);

    Route::get('show-product-by-category-id/{id}/{parentId}', [
        'uses' => 'HomeController@showProduct',
        'as' => 'show-product'
    ]);

    Route::get('show-product-by-price/{parentId}', [
        'uses' => 'HomeController@showProductByPrice',
        'as' => 'show-product-by-price'
    ]);

    Route::get('show-detail-product/{id}/{parentId}', [
        'uses' => 'HomeController@showDetailProduct',
        'as' => 'show-detail-product'
    ]);

    Route::get('show-cart-detail', [
        'uses' => 'ShoppingCartController@showCartDetail',
        'as' => 'show-cart-detail'
    ]);

    Route::get('add-to-cart', [
        'uses' => 'ShoppingCartController@addToCart',
        'as' => 'add-to-cart'
    ]);

    Route::get('add-to-cart-simple/{productId}', [
        'uses' => 'ShoppingCartController@addToCartSimple',
        'as' => 'add-to-cart-simple'
    ]);

    Route::get('remove-product-from-cart/{rowId}', [
        'uses' => 'ShoppingCartController@removeProductFromCart',
        'as' => 'remove-product-from-cart'
    ]);

    Route::get('update-quantity-product-from-cart/{rowId}', [
        'uses' => 'ShoppingCartController@updateQuantityProductFromCart',
        'as' => 'update-quantity-product-from-cart'
    ]);

    Route::post('checkout', [
        'uses' => 'ShoppingCartController@checkout',
        'as' => 'checkout'
    ]);

    Route::get('list-article', [
        'uses' => 'ArticleController@listArticle',
        'as' => 'list-article'
    ]);

    Route::get('detail-article/{id}', [
        'uses' => 'ArticleController@showDetailArticle',
        'as' => 'detail-article'
    ]);

    Route::get('send-comment-article/{id}/{parentId}', [
        'uses' => 'ArticleController@sendComment',
        'as' => 'send-comment',
    ]);

    Route::get('send-comment-product/{id}/{parentId}', [
        'uses' => 'HomeController@sendComment',
        'as' => 'send-comment-product',
    ]);

    Route::get('send-comment-product-non-rating/{id}/{parentId}', [
        'uses' => 'HomeController@sendCommentNonRating',
        'as' => 'send-comment-product-non-rating',
    ]);

    Route::get('search', [
        'uses' => 'HomeController@search',
        'as' => 'search',
    ]);

    Route::get('add-to-wishlist/{id}', [
        'uses' => 'HomeController@addToWishList',
        'as' => 'add-to-wishlist',
    ]);

    Route::get('list-wishlist/', [
        'uses' => 'HomeController@listWishList',
        'as' => 'list-wishlist',
    ]);

    Route::get('remove-from-wishlist/{id}', [
        'uses' => 'HomeController@removeFromWishList',
        'as' => 'remove-from-wishlist',
    ]);

    Route::post('change-information',[
        'uses' => 'HomeController@changeInformation',
        'as' => 'change-information'
    ]);

    Route::post('change-password',[
        'uses' => 'HomeController@changePassword',
        'as' => 'change-password'
    ]);

    Route::get('show-detail-order/{id}', [
        'uses' => 'HomeController@showDetailOrder',
        'as' => 'show-detail-order'
    ]);

    Route::get('cancel-order/{id}', [
        'uses' => 'HomeController@cancelOrder',
        'as' => 'cancel-order'
    ]);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('admin.login');
});

app/Models/Product.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @method create(array $dataInsert)
 * @method orderBy(string $string, string $string1)
 * @method findOrFail($id)
 */
class Product extends Model
{
    use SoftDeletes;

    protected $table = 'products';

    protected $guarded = [];

    // relationship

    public function categories(){
        return $this->belongsTo(Category::class,'category_id','id');
    }

    public function users(){
        return $this->belongsTo(User::class,'admin_id','id');
    }

    public function tags(){
        return $this->belongsToMany(Tag::class,'product_tags','product_id','tag_id');
    }

    public function images(){
        return $this->hasMany(Image::class,'product_id','id');
    }

    public function ratings()
    {
        return $this->hasMany(Rating::class, 'product_id', 'id');
    }

    // accessors

    public function getAverageStarAttribute()
    {
        return $this->times_rating != 0 ? ( (float) $this->total_rating / $this->times_rating ) : 0;
    }

}

resources/views/components-customer/list-product/beadcrumbs.blade.php
<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <ul>
                <li class="home">
                    <a href="{{ route('frontend.index') }}" title="Go to Home Page">Home</a>
                    <span>|</span>
                </li>
                <li class="category3">
                    <strong>{{ $categorySelected->name }}</strong>
                </li>
            </ul>
        </div>
    </div>
</div>

resources/views/components-customer/list-product/box-left.blade.php
<div id="box-left" class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
    <div class="block block-layered-nav">
        <div class="block-title">
            <strong><span>{{ $categorySelected->name }}</span></strong>
        </div>
        <div class="block-content">
            <dl id="narrow-by-list">
                <dt style="width: 268px" class="category-children active-category"
                    data-action="{{ route('frontend.show-product', ['id' => 0, 'parentId' => $id]) }}">
                    Tất cả
                </dt>
                @foreach($categorySelected->categoryChildren as $key => $category)
                    <dt style="width: 268px" class="category-children"
                        data-action="{{ route('frontend.show-product', ['id' => $category->id, 'parentId' => $id]) }}">
                        {{ $category->name }}
                    </dt>
                @endforeach
            </dl>
        </div>
        <div class="block-title-shop-by">
            <strong><span>Shop by</span></strong>
        </div>
        <div class="block-content">
            <dl id="narrow-by-list">
                <dt id="tab2" class="tab-accordion accordion-open"> Price</dt>
                <dd class="tabcontent2">
                    <div class="price">
                        <div class="range-wrap"><div id="slider-range" class="ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all"><div class="ui-slider-range ui-widget-header" style="left: 0%; width: 100%;"></div><a class="ui-slider-handle ui-state-default ui-corner-all" href="#" style="left: 0%;"></a><a class="ui-slider-handle ui-state-default ui-corner-all" href="#" style="left: 100%;"></a></div>
                        </div>
                        <div class="text-box"><div class="price-from">
                                $ <input type="text" id="minPrice" class="priceTextBox" value="0"></div>
                            <div class="price-to">
                                <input type="text" id="maxPrice" class="priceTextBox" value="30000000" style="width: 85px !important;">
                            </div>
                            <a class="go fillter"
                               href="javascript:void(0)"
                               style="margin-left: 0px !important; margin-top: 10px !important;"
                               data-action="{{ route('frontend.show-product-by-price', ['parentId' => $id]) }}"
                            >
                                Fillter
                            </a>
                            <input type="hidden" id="amount" readonly="readonly" style="background:none; border:none;" value="$0 - $30000000">
                        </div>
                    </div>
                </dd>
            </dl>
        </div>
    </div>
    <div class="block box-banner">
        <div id="box-banner" class="carousel slide" data-ride="carousel" data-interval="1500"><ol class="carousel-indicators">
                <li class="" data-target="#box-banner" data-slide-to="0"></li>
                <li data-target="#box-banner" data-slide-to="1" class="active"></li>
                <li data-target="#box-banner" data-slide-to="2" class=""></li>
            </ol>
            <div class="carousel-inner">
                <div class="item"><a href="detail.html"><img src="store/images/banner13.png" alt="banner"></a>
                    <div class="std">
                        <span class="t1">up to 45%</span>
                        <span class="t2">Nokia Lumia 920</span>
                        <span class="t3">At verov eos et accusamus et iusto ods un dignissimos ducimus qui blan ditiis prasixer esentium</span>
                    </div>
                    <a class="gt-shop" href="#">Shop Now</a>
                </div>
                <div class="item active"><a href="detail.html"><img src="store/images/banner14.png" alt="banner"></a>
                    <div class="std">
                        <span class="t1">up to 50%</span>
                        <span class="t2">Nokia Lumia 920</span>
                        <span class="t3">At verov eos et accusamus et iusto ods un dignissimos ducimus qui blan ditiis prasixer esentium</span>
                    </div>
                    <a class="gt-shop" href="#">Shop Now</a>

                </div>
                <div class="item"><a href="detail.html"><img src="store/images/banner15.png" alt="banner"></a>
                    <div class="std">
                        <span class="t1">up to 80%</span>
                        <span class="t2">Nokia Lumia 920</span>
                        <span class="t3">At verov eos et accusamus et iusto ods un dignissimos ducimus qui blan ditiis prasixer esentium</span>
                    </div>
                    <a class="gt-shop" href="#">Shop Now</a>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/components-customer/list-product/main.blade.php
<div id="main" class="col-lg-9 col-md-9 col-sm-8 col-xs-12 col-main">
    <div class="wrap-banner-cate">
        <div class="cate-img">
            <img src="{{ $categorySelected->banners->count() ? $categorySelected->banners[0]->path : 'store/images/banner-2.png' }} " alt="">
        </div>
    </div>
    <div class="page-title category-title">
        <h1>Mobile</h1>
    </div>
    <div id="catalog-listing">
        <div class="category-products page-product-list">
            <div class="toolbar-top">
                <div class="toolbar">
                    <div class="pager">
                        <div class="pages">

                        </div>
                        <!--<label class="item-pp"></label>-->
                    </div>
                </div>
            </div>
            <ul class="products-grid row">
                @foreach($listProduct as $product)
                    <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12 item">
                        <div class="item-wrap">
                            <div class="item-image">
                                <a class="product-image no-touch" href="#" title="{{ $product->name }}">
                                    <img style="width: 165px; height: 165px" class="first_image" src="{{ $product->avatar }}" alt="Product demo">
                                </a>
                                <div class="item-btn">
                                    <div class="box-inner">
                                        @if(\Auth::check())
                                            <a title="Add to wishlist" href="{{ route('frontend.add-to-wishlist', ['id' => $product->id]) }}"
                                               class="link-wishlist" style="background: {{ $listWishList->contains($product->id) ? 'yellow' : ''}} ">&nbsp;</a>
                                        @else
                                            <a title="Add to wishlist" href="javascript:void();" class="open-login-form link-wishlist">&nbsp;</a>
                                        @endif
                                        <span class="qview"><a href="{{ route('frontend.show-detail-product', ['id' => $product->id, 'parentId' => $product->category_id]) }}"></a>
										  <a class="vt_quickview_handler"
                                             data-original-title="Quick View"
                                             data-placement="left"
                                             data-toggle="tooltip"
                                             href="{{ route('frontend.show-detail-product', ['id' => $product->id, 'parentId' => $product->category_id]) }}">
                                              <span>Quick View</span>
                                          </a>
                                        </span>
                                    </div>
                                </div>
                                <a title="Add to cart" class="btn-cart" href="{{ route('frontend.add-to-cart-simple', ['productId' => $product->id]) }}">&nbsp;</a>
                            </div>
                            <div class="pro-info">
                                <div class="pro-inner">
                                    <div class="pro-title product-name"><a href="{{ route('frontend.show-detail-product', ['id' => $product->id, 'parentId' => $product->category_id]) }}">{{ $product->name }}</a></div>
                                    <div class="pro-content">
                                        <div class="wrap-price">
                                            <div class="price-box">
												<span class="regular-price">
												<span class="price">{{ number_format($product->price,2,",",".") }} VND</span></span>
                                            </div>
                                        </div>
                                        <div class="ratings">
                                            <div class="rating-box">
                                                <div class="rating" style="width: {{ $product->average_star * 20 }}%"></div>
                                            </div>
                                            <span class="amount"><a href="javascript:void();">{{ $product->times_rating }} đánh giá</a></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--end item wrap -->
                    </li>
                @endforeach
            </ul>
            <div class="toolbar-bottom">
                <div class="toolbar">
                    <div class="pager">
                        <div class="pages">
                            <strong>Pages</strong>
                            <ol>
                                <li class="current">1</li>
                                <li><a href="grid.html?p=2">2</a></li>
                                <li>
                                    <a class="next" href="grid.html?p=2" title="Next">
                                        &nbsp;                                 </a>
                                </li>
                            </ol>
                        </div>
                        <!--<label class="item-pp"></label>-->
                    </div>
                    <div class="sorter">
                        <label>View as</label>
                        <p class="view-mode">
                            <strong title="Grid" class="grid">Grid</strong>
                            <a href="grid.html?mode=list" title="List" class="list">List</a>
                        </p>
                        <div class="sort-by">
                            <label>Sort By</label>
                            <div class="wrap-sb">
                                <div class="selected-order">Position</div>
                                <ul class="select-order">
                                    <li><a href="grid.html?dir=asc&amp;order=position" class="selected">Position</a></li>
                                    <li><a href="grid.html?dir=asc&amp;order=name">Name</a></li>
                                    <li><a href="grid.html?dir=asc&amp;order=price">Price</a></li>
                                </ul>
                            </div>
                            <a class="desc" href="grid.html?dir=desc&amp;order=position" title="Set Descending Direction">
                                <!--<img src="" alt="" class="v-middle" />-->
                            </a>
                        </div>
                        <div class="limiter">
                            <label>Show</label>
                            <div class="wrap-show">
                                <div class="selected-limiter">9</div>
                                <ul class="select-limiter">
                                    <li><a href="grid.html?limit=9" class="selected">9</a></li>
                                    <li><a href="grid.html?limit=12">12</a></li>
                                    <li><a href="grid.html?limit=24">24</a></li>
                                    <li><a href="grid.html?limit=36">36</a></li>
                                </ul>
                            </div>
                            <label class="stylepp">per page</label>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

resources/views/components-customer/list-product/view-list-product.blade.php
<ul class="products-grid row">
    @foreach($listProduct as $product)
        <li class="col-lg-3 col-md-3 col-sm-6 col-xs-12 item">
            <div class="item-wrap">
                <div class="item-image">
                    <a class="product-image no-touch" href="#" title="{{ $product->name }}">
                        <img style="width: 165px; height: 165px" class="first_image" src="{{ $product->avatar }}" alt="Product demo">
                    </a>
                    <div class="item-btn">
                        <div class="box-inner">
                            @if(\Auth::check())
                                <a title="Add to wishlist" href="{{ route('frontend.add-to-wishlist', ['id' => $product->id]) }}"
                                   class="link-wishlist" style="background: {{ $listWishList->contains($product->id) ? 'yellow' : ''}} ">&nbsp;</a>
                            @else
                                <a title="Add to wishlist" href="javascript:void();" class="open-login-form link-wishlist">&nbsp;</a>
                            @endif
                            <span class="qview">
                                <a href="{{ route('frontend.show-detail-product', ['id' => $product->id, 'parentId' => $product->category_id]) }}"></a>
                                <a class="vt_quickview_handler"
                                   data-original-title="Quick View"
                                   data-placement="left"
                                   data-toggle="tooltip"
                                   href="{{ route('frontend.show-detail-product', ['id' => $product->id, 'parentId' => $product->category_id]) }}">
                                    <span>Quick View</span>
                                </a>
                            </span>
                        </div>
                    </div>
                    <a title="Add to cart" class="btn-cart" href="{{ route('frontend.add-to-cart-simple', ['productId' => $product->id]) }}">&nbsp;</a>
                </div>
                <div class="pro-info">
                    <div class="pro-inner">
                        <div class="pro-title product-name"><a href="{{ route('frontend.show-detail-product', ['id' => $product->id, 'parentId' => $product->category_id]) }}">{{ $product->name }}</a></div>
                        <div class="pro-content">
                            <div class="wrap-price">
                                <div class="price-box">
												<span class="regular-price">
												<span class="price">{{ number_format($product->price,2,",",".") }} VND</span></span>
                                </div>
                            </div>
                            <div class="ratings">
                                <div class="rating-box">
                                    <div class="rating" style="width: {{ $product->average_star * 20 }}%"></div>
                                </div>
                                <span class="amount"><a href="javascript:void();">{{ $product->times_rating }} đánh giá</a></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--end item wrap -->
        </li>
    @endforeach
</ul>