routes/admin.php
<?php
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->namespace('Admin')->group(function (){

    // login
    Route::get('/login', [
        'as' => 'admin.login',
        'uses' => 'AdminController@login'
    ]);
    Route::post('/login', [
        'as' => 'admin.login',
        'uses' => 'AdminController@post_login'
    ]);

    // Dashboard
    Route::get('dashboard',[
        'uses' => 'MemberController@showDashboard',
        'as' => 'admin.dashboard',
        'middleware' => 'can:view-dashboard'
    ]);

    // Category
    Route::prefix('categories')->group(function (){
        Route::get('/',[
            'uses' => 'CategoryController@index',
            'as' => 'categories.index',
            'middleware' => 'can:view-category'
        ]);
        Route::get('list-category',[
            'uses' => 'CategoryController@listCategory',
            'as' => 'categories.list'
        ]);
        Route::get('list-parent',[
            'uses' => 'CategoryController@listParent',
            'as' => 'categories.list-parent'
        ]);
        Route::post('store',[
            'uses' => 'CategoryController@store',
            'as' => 'categories.store',
            'middleware' => 'can:add-category'
        ]);
        Route::post('update/{id}',[
            'uses' => 'CategoryController@update',
            'as' => 'categories.update',
            'middleware' => 'can:edit-category'
        ]);
        Route::get('get-category/{id}',[
            'uses' => 'CategoryController@getCategory',
            'as' => 'categories.get-category'
        ]);
        Route::get('destroy/{id}',[
            'uses' => 'CategoryController@destroy',
            'as' => 'categories.destroy',
            'middleware' => 'can:delete-category'
        ]);
        Route::get('change-status/{id}',[
            'uses' => 'CategoryController@changeStatus',
            'as' => 'categories.change-status',
            'middleware' => 'can:edit-category'
        ]);
        Route::get('tree-view',[
            'uses'=>'CategoryController@treeView',
            'as'=>'categories.tree-view'
        ]);
    });

    // Product
    Route::prefix('products')->group(function(){
        Route::get('/',[
            'uses' => 'ProductController@index',
            'as' => 'products.index',
            'middleware' => 'can:view-product'
        ]);
        Route::get('list-product',[
            'uses'=>'ProductController@listProduct',
            'as'=>'products.list'
        ]);
        Route::get('change-status/{id}',[
            'uses'=>'ProductController@changeStatus',
            'as'=>'products.change-status',
            'middleware' => 'can:edit-product'
        ]);
        Route::post('store',[
            'uses'=>'ProductController@store',
            'as'=>'products.store',
            'middleware' => 'can:add-product'
        ]);
        Route::post('update/{id}',[
            'uses'=>'ProductController@update',
            'as'=>'products.update',
            'middleware' => 'can:edit-product'
        ]);
        Route::get('edit/{id}',[
            'uses'=>'ProductController@edit',
            'as'=>'products.edit',
            'middleware' => 'can:edit-product'
        ]);
        Route::get('destroy/{id}',[
            'uses'=>'ProductController@destroy',
            'as'=>'products.destroy',
            'middleware' => 'can:delete-product'
        ]);
    });

    // Article
    Route::prefix('articles')->group(function () {
        Route::get('/',[
            'uses' => 'ArticleController@index',
            'as' => 'articles.index',
            'middleware' => 'can:view-article'
        ]);
        Route::get('/create',[
            'uses' => 'ArticleController@create',
            'as' => 'articles.create',
            'middleware' => 'can:add-article'
        ]);
        Route::post('/store',[
            'uses' => 'ArticleController@store',
            'as' => 'articles.store',
            'middleware' => 'can:add-article'
        ]);
        Route::get('/{id}/edit', [
            'uses' => 'ArticleController@edit',
            'as' => 'articles.edit',
            'middleware' => 'can:edit-article'
        ]);
        Route::post('/{id}/update', [
            'uses' => 'ArticleController@update',
            'as' => 'articles.update',
            'middleware' => 'can:edit-article'
        ]);
        Route::get('/{id}/destroy',[
            'uses' => 'ArticleController@destroy',
            'as' => 'articles.destroy',
            'middleware' => 'can:delete-article'
        ]);
    });

    // users
    Route::prefix('users')->group(function () {
        Route::get('/', [
            'uses' => 'UserController@index',
            'as' => 'users.index',
            'middleware' => 'can:view-user'
        ]);

        Route::get('/create',[
            'uses' => 'UserController@create',
            'as' => 'users.create',
            'middleware' => 'can:add-user'
        ]);
        Route::post('/store',[
            'uses' => 'UserController@store',
            'as' => 'users.store',
            'middleware' => 'can:add-user'
        ]);
        Route::get('/{id}/edit', [
            'uses' => 'UserController@edit',
            'as' => 'users.edit',
            'middleware' => 'can:edit-user'
        ]);
        Route::post('/{id}/update', [
            'uses' => 'UserController@update',
            'as' => 'users.update',
            'middleware' => 'can:edit-user'
        ]);
        Route::get('/{id}/destroy',[
            'uses' => 'UserController@destroy',
            'as' => 'users.destroy',
            'middleware' => 'can:delete-user'
        ]);
    });

    // roles
    Route::prefix('roles')->group(function () {
        Route::get('/', [
            'uses' => 'RoleController@index',
            'as' => 'roles.index',
            'middleware' => 'can:view-role'
        ]);

        Route::get('/create',[
            'uses' => 'RoleController@create',
            'as' => 'roles.create',
            'middleware' => 'can:add-role'
        ]);
        Route::post('/store',[
            'uses' => 'RoleController@store',
            'as' => 'roles.store',
            'middleware' => 'can:add-role'
        ]);
        Route::get('/{id}/edit', [
            'uses' => 'RoleController@edit',
            'as' => 'roles.edit',
            'middleware' => 'can:edit-role'
        ]);
        Route::post('/{id}/update', [
            'uses' => 'RoleController@update',
            'as' => 'roles.update',
            'middleware' => 'can:edit-role'
        ]);
        Route::get('/{id}/destroy',[
            'uses' => 'RoleController@destroy',
            'as' => 'roles.destroy',
            'middleware' => 'can:delete-role'
        ]);
    });

    Route::prefix('orders')->group(function () {
        Route::get('/', [
            'uses' => 'OrderController@index',
            'as' => 'orders.index'
        ]);

        Route::get('detail/{id}', [
            'uses' => 'OrderController@detail',
            'as' => 'orders.detail'
        ]);

        Route::get('status-to-transport/{id}', [
            'uses' => 'OrderController@changeStatusToTransport',
            'as' => 'orders.status-to-transport'
        ]);

        Route::get('status-to-done/{id}', [
            'uses' => 'OrderController@changeStatusToDone',
            'as' => 'orders.status-to-done'
        ]);
    });
});

routes/frontend.php
<?php
use Illuminate\Support\Facades\Route;

Route::prefix('frontend')->as('frontend.')->namespace('Frontend')->group(function () {
    Route::get('/',[
        'uses' => 'HomeController@index',
        'as' => 'index'
    ]);

    Route::post('login', [
        'uses' => 'HomeController@login',
        'as' => 'login'
    ]);

    Route::post('register', [
        'uses' => 'HomeController@register',
        'as' => 'register'
    ]);

    Route::get('logout', [
        'uses' => 'HomeController@logout',
        'as' => 'logout'
    ]);

    Route::get('show-categories/{slug}/{id}', [
        'uses' => 'HomeController@showCategory',
        'as' => 'show-categories'
    ]);

    Route::get('show-product-by-category-id/{id}/{parentId}', [
        'uses' => 'HomeController@showProduct',
        'as' => 'show-product'
    ]);

    Route::get('show-product-by-price/{parentId}', [
        'uses' => 'HomeController@showProductByPrice',
        'as' => 'show-product-by-price'
    ]);

    Route::get('show-detail-product/{id}/{parentId}', [
        'uses' => 'HomeController@showDetailProduct',
        'as' => 'show-detail-product'
    ]);

    Route::get('show-cart-detail', [
        'uses' => 'ShoppingCartController@showCartDetail',
        'as' => 'show-cart-detail'
    ]);

    Route::get('add-to-cart', [
        'uses' => 'ShoppingCartController@addToCart',
        'as' => 'add-to-cart'
    ]);

    Route::get('add-to-cart-simple/{productId}', [
        'uses' => 'ShoppingCartController@addToCartSimple',
        'as' => 'add-to-cart-simple'
    ]);

    Route::get('remove-product-from-cart/{rowId}', [
        'uses' => 'ShoppingCartController@removeProductFromCart',
        'as' => 'remove-product-from-cart'
    ]);

    Route::get('update-quantity-product-from-cart/{rowId}', [
        'uses' => 'ShoppingCartController@updateQuantityProductFromCart',
        'as' => 'update-quantity-product-from-cart'
    ]);

    Route::post('checkout', [
        'uses' => 'ShoppingCartController@checkout',
        'as' => 'checkout'
    ]);

    Route::get('list-article', [
        'uses' => 'ArticleController@listArticle',
        'as' => 'list-article'
    ]);

    Route::get('detail-article/{id}', [
        'uses' => 'ArticleController@showDetailArticle',
        'as' => 'detail-article'
    ]);

    Route::get('send-comment-article/{id}/{parentId}', [
        'uses' => 'ArticleController@sendComment',
        'as' => 'send-comment',
    ]);

    Route::get('send-comment-product/{id}/{parentId}', [
        'uses' => 'HomeController@sendComment',
        'as' => 'send-comment-product',
    ]);

    Route::get('send-comment-product-non-rating/{id}/{parentId}', [
        'uses' => 'HomeController@sendCommentNonRating',
        'as' => 'send-comment-product-non-rating',
    ]);

    Route::get('search', [
        'uses' => 'HomeController@search',
        'as' => 'search',
    ]);

    Route::get('add-to-wishlist/{id}', [
        'uses' => 'HomeController@addToWishList',
        'as' => 'add-to-wishlist',
    ]);

    Route::get('list-wishlist/', [
        'uses' => 'HomeController@listWishList',
        'as' => 'list-wishlist',
    ]);

    Route::get('remove-from-wishlist/{id}', [
        'uses' => 'HomeController@removeFromWishList',
        'as' => 'remove-from-wishlist',
    ]);

    Route::post('change-information',[
        'uses' => 'HomeController@changeInformation',
        'as' => 'change-information'
    ]);

    Route::post('change-password',[
        'uses' => 'HomeController@changePassword',
        'as' => 'change-password'
    ]);

    Route::get('show-detail-order/{id}', [
        'uses' => 'HomeController@showDetailOrder',
        'as' => 'show-detail-order'
    ]);

    Route::get('cancel-order/{id}', [
        'uses' => 'HomeController@cancelOrder',
        'as' => 'cancel-order'
    ]);
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('admin.login');
});

resources/views/customer/cart-detail.blade.php
@extends('layouts.master-customer')

@section('content')
    <div class="card">
        <input type="hidden" id="alert-message" value="{{ \Session::get('alert-message') ?? 2 }}">
        @php
            \Session::put('alert-message', 2);
        @endphp
        <div class="row">
            <div class="col-md-8 cart">
                <div class="title">
                    <div class="row">
                        <div class="col">
                            <h4><b>Shopping Cart</b></h4>
                        </div>
                        <div class="col align-self-center text-right text-muted">{{ Cart::count() }} SẢN PHẨM</div>
                    </div>
                </div>
                <table class="table table-hover">
                    <thead>
                    <tr style="font-weight: bolder; color: black">
                        <th scope="col"></th>
                        <th scope="col">Sản phẩm</th>
                        <th scope="col">Số lượng</th>
                        <th scope="col">Đơn giá</th>
                        <th scope="col">Thành tiền</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach(Cart::content() as $item)
                        <tr>
                            <input type="hidden" value="{{ $item->rowId }}">
                            <th scope="row">
                                <img class="avatar-product" src="{{ $item->options->image }}">
                            </th>
                            <td style="width: 100px">{{ $item->name }}</td>
                            <td>
                                <input style="width: 50px" type="number" value="{{ $item->qty }}">
                                <a class="update-quantity" href="{{ route('frontend.update-quantity-product-from-cart', ['rowId' => $item->rowId]) }}" style="display: block; margin-left: -10px; font-size: 11px ">Cập nhật</a>
                            </td>
                            <td>
                                <div class="price-box">
                                    <div style="font-weight: bolder; color: black !important;">{{ number_format( $item->price,2,",",".") }}
                                        VND
                                    </div>
                                    @if($item->options->sale > 0)
                                        <div>Sale: - {{ $item->options->sale }} %</div>
                                        <p class="special-price">
                                            <span class="price">{{ number_format($item->options->price_origin,2,",",".") }} VND</span>
                                        </p>
                                    @endif
                                </div>
                            </td>
                            <td>
                                <div class="price-box" style="font-weight: bolder; color: black !important;">
                                    <div>{{ number_format($item->qty * $item->price ,2,",",".") }} VND</div>
                                </div>
                            </td>
                            <td>
                                <a href="{{ route('frontend.remove-product-from-cart', ['rowId' => $item->rowId]) }}">Xoá</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="row" >
                    <div class="col" style="color: black; font-weight: bolder; text-transform: uppercase; margin-top: 50px">
                        <h4>Tổng tiền cần thanh toán</h4>
                    </div>
                    <div class="col text-right" style="color: black; font-weight: bolder">{{ Cart::subtotal() }} VND</div>
                </div>
                <div class="back-to-shop"><a href="{{ route('frontend.index') }}">&leftarrow;</a><span class="text-muted">Back to shop</span></div>
            </div>
            <div class="col-md-4 summary">
                <form method="POST" action="{{ route('frontend.checkout') }}">
                    @csrf
                    <div class="form-group">
                        <label for="name">Họ và tên</label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="Họ và tên" value="{{ old('name') }}">
                        <div class="text-danger font-size-h6"> {!!$errors->first('name')!!}</div>
                    </div>
                    <div class="form-group">
                        <label for="phone">Số điện thoại</label>
                        <input type="text" class="form-control" id="phone" name="phone" placeholder="Số điện thoại" value="{{ old('phone') }}">
                        <div class="text-danger font-size-h6"> {!!$errors->first('phone')!!}</div>
                    </div>
                    <div class="form-group">
                        <label for="address">Địa chỉ</label>
                        <input type="text" class="form-control" id="address" name="address" placeholder="Địa chỉ" value="{{ old('address') }}">
                        <div class="text-danger font-size-h6"> {!!$errors->first('address')!!}</div>
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Email" value="{{ old('email') }}">
                        <div class="text-danger font-size-h6"> {!!$errors->first('email')!!}</div>
                    </div>
                    <div class="form-group">
                        <label for="note">Ghi chú thêm</label>
                        <textarea name="note" id="note" cols="30" rows="5">{{ old('note') }}</textarea>
                    </div>
                    <button style="font-size: 13px;
                                font-weight: bolder;
                                background-color: #000;
                                border-color: #000;
                                color: white;
                                width: 100%;
                                margin-top: 4vh;
                                padding: 1vh;
                                border-radius: 0" class="btn" type="submit">
                        Đặt hàng
                    </button>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('css')
    <link rel="stylesheet" type="text/css" href="css/frontend/cart-detail.css"/>
@endsection

@section('js')
    <script src="js/frontend/cart-detail.js"></script>
@endsection

resources/views/customer/detail-article.blade.php
@extends('layouts.master-customer')

@section('content')
    <div class="breadcrumbs">
        <div class="container">
            <div class="row">
                <ul>
                    <li class="home">
                        <a href="{{ route('frontend.index') }}" title="Go to Home Page">Home</a>
                        <span>|</span>
                    </li>
                    <li class="category3">
                        <a href="{{ route('frontend.list-article') }}">Bài viết</a>
                        <span>|</span>
                    </li>
                    <li class="category3">
                        <strong>{{ $article->name }}</strong>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <!-- Title -->
                <h1 class="mt-4" style="font-weight: bolder; color: black">{{ $article->name }}</h1>

                <!-- Author -->
                <p class="lead">
                    by
                    <a href="#">{{ $article->user->name }}</a>
                </p>

                <hr>

                <!-- Date/Time -->
                <p>Posted on {{ $article->created_at }}</p>

                <hr>

                <!-- Preview Image -->
                <img class="img-fluid rounded" src="{{ $article->avatar }}" alt="">

                <hr>

                <!-- Post Content -->
                <div>
                    {!! $article->content !!}
                </div>
                <hr>
                <!-- Comments Form -->
                <div class="card my-4">
                    <h5 class="card-header" style="color: black">Để lại bình luận bên dưới</h5>
                    <div class="card-body">
                        <form>
                            @csrf
                            <input type="hidden" class="id-user" value="{{ \Auth::id() ?? 0 }}">
                            <div class="form-group">
                                <textarea class="form-control content" rows="3" ></textarea>
                            </div>
                            <button type="button" class="btn btn-primary send-comment"
                                    data-action="{{ route('frontend.send-comment', ['id' => $article->id, 'parentId' => 0]) }}">
                                Gửi
                            </button>
                        </form>
                    </div>
                </div>

                <!-- Single Comment -->
                @php
                    use Carbon\Carbon;
                    Carbon::setLocale('vi');
                    $now = Carbon::now();
                @endphp
                <div class="total-comment">Tổng số bình luận: {{ $listArticleComment->count() }}</div>
                @foreach($listArticleComment as $key => $comment)
                    @if($key <= 10 && $comment->parent_id == 0)
                        <div class="media mb-4">
                            <div class="media-body">
                                <span class="mt-0" style="color: black; font-size: 18px">{{ $comment->user->name }}</span> <span>{{ $comment->time }}</span>
                                <div style="margin-top: 12px; margin-bottom: 20px">{!! nl2br($comment->content) !!} </div>
                                <hr>

                                @php
                                    $listChildren = $comment->articleCommentChildren->reverse();
                                @endphp

                                @foreach($listChildren as $children)
                                    <div class="row" style="margin-bottom: 10px">
                                        <div class="col-md-2"></div>
                                        <div class="col-md-10">
                                            <div><span style="color: black; margin-right: 10px">{{ $children->user->name }}</span><span>{{ $children->created_at->diffForHumans($now) }}</span></div>
                                            <div>{!! nl2br($children->content) !!}</div>
                                            <hr>
                                        </div>
                                    </div>
                                @endforeach
                                <span class="answer"><small style="color: #4a90e2; cursor: pointer">Trả lời</small></span>
                            </div>
                            <div style="display: none">
                                <div class="form-group" style="margin-top: 5px">
                                    <textarea class="form-control content" rows="3"></textarea>
                                </div>
                                <button type="button" class="btn btn-primary send-comment"
                                        data-action="{{ route('frontend.send-comment',
                                                        ['id' => $article->id, 'parentId' => $comment->id]
                                                        ) }}">
                                    Gửi
                                </button>
                            </div>
                            <hr>
                        </div>
                    @endif
                @endforeach
            </div>

            <!-- Sidebar Widgets Column -->
            @include('components-customer.list-article.content-right')
        </div>
        <!-- /.row -->

    </div>
@endsection

@section('css')
    <link rel="stylesheet" type="text/css" href="css/frontend/list-blog.css"/>
    <link rel="stylesheet" type="text/css" href="css/frontend/blog-detail.css"/>
@endsection

@section('js')
    <script src="js/frontend/detail-article.js"></script>
@endsection

resources/views/customer/detail-product.blade.php
@extends('layouts.master-customer')

@section('content')
    <div class="content">
        @include('components-customer.list-product.beadcrumbs')
        <div class="container">
            <div class="row">
                <div class="row">
                    @include('components-customer.detail-product.box-left')
                    @include('components-customer.detail-product.main')
                </div>
            </div>
        </div>
    </div>
@endsection

@section('css')

@endsection

@section('js')
    <script src="js/frontend/detail-product.js"></script>
@endsection

resources/views/customer/index.blade.php
@extends('layouts.master-customer')

@section('content')
    <div id="box-content">
        @include('components-customer.home-content.container')
        @include('components-customer.home-content.position-10')
        @include('components-customer.home-content.position-03')
        @include('components-customer.home-content.position-02')
        @include('components-customer.home-content.position-04')
        @include('components-customer.home-content.position-06')
        @include('components-customer.home-content.position-08')
        @include('components-customer.home-content.position-09')
    </div>
@endsection

resources/views/customer/list-article.blade.php
@extends('layouts.master-customer')

@section('content')
    <div class="breadcrumbs">
        <div class="container">
            <div class="row">
                <ul>
                    <li class="home">
                        <a href="{{ route('frontend.index') }}" title="Go to Home Page">Home</a>
                        <span>|</span>
                    </li>
                    <li class="category3">
                        <strong>Bài viết</strong>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8">
                <h1 class="my-4 title-page">BLOG
                    <hr style="border: 1px solid black">
                </h1>

                <!-- Blog Post -->
                @foreach($listArticle as $article)
                    <div class="row card blog-simple">
                        <div class="card-body">
                            <div class="col-md-4">
                                <img class="card-img-top" src="{{ $article->avatar }}" alt="Card image cap">
                            </div>
                            <div class="col-md-8">
                                <h2 class="card-title">
                                    <a href="{{ route('frontend.detail-article', ['id' => $article->id]) }}">{{ $article->name }}</a>
                                </h2>
                                <div class="card-text">
                                    {!! $article->description !!}
                                </div>
                                <div>
                                    Posted on <span style="color: black">{{ $article->created_at }}</span> by <span style="color: black; font-weight: bolder">{{ $article->user->name }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach

                <!-- Pagination -->
            </div>

            <!-- Sidebar Widgets Column -->
            @include('components-customer.list-article.content-right')
        </div>
        <!-- /.row -->

    </div>
@endsection

@section('css')
    <link rel="stylesheet" type="text/css" href="css/frontend/list-blog.css"/>
@endsection

@section('js')
    <script src="js/frontend/cart-detail.js"></script>
@endsection

resources/views/customer/list-product.blade.php
@extends('layouts.master-customer')

@section('content')
    <div class="content">
        @include('components-customer.list-product.beadcrumbs')
        <div class="container">
            <div class="row">
                <div class="row">
                   @include('components-customer.list-product.box-left')
                   @include('components-customer.list-product.main')
                </div>
            </div>
        </div>
    </div>
@endsection

@section('css')
    <link rel="stylesheet" type="text/css" href="css/frontend/list-product.css"/>
@endsection

@section('js')
    <script src="js/frontend/list-product.js"></script>
@endsection